export interface Surah {
    name: string;
    code: string;
    count: number;
    fullName?: string;
}

export const surah = (surahName: string): Surah | undefined => {
    return asuar.find((surah: Surah) => surah.name === surahName)
}

export const asuar: Surah[] = [
    { name: 'حمد',      code: '1',   count: 7    },
    { name: 'بقره',     code: '2',   count: 286  },
    { name: 'آل عمران', code: '3',   count: 200  },
    { name: 'نساء',     code: '4',   count: 176  },
    { name: 'مائده',    code: '5',   count: 120  },
    { name: 'انعام',    code: '6',   count: 165  },
    { name: 'اعراف',    code: '7',   count: 206  },
    { name: 'انفاق',    code: '8',   count: 75   },
    { name: 'توبه',     code: '9',   count: 129  },
    { name: 'یونس',     code: '10',  count: 109 },
    { name: 'هود',      code: '11',  count: 123 },
    { name: 'یوسف',     code: '12',  count: 111 },
    { name: 'رعد',      code: '13',  count: 43  },
    { name: 'ابراهیم',  code: '14',  count: 52  },
    { name: 'حجر',      code: '15',  count: 99  },
    { name: 'نحل',      code: '16',  count: 128 },
    { name: 'اسراء',    code: '17',  count: 111 },
    { name: 'کهف',      code: '18',  count: 110 },
    { name: 'مریم',     code: '19',  count: 98  },
    { name: 'طه',       code: '20',  count: 135 },
    { name: 'انبیاء',   code: '21',  count: 112 },
    { name: 'حج',       code: '22',  count: 78  },
    { name: 'مومنون',   code: '23',  count: 118 },
    { name: 'نور',      code: '24',  count: 64  },
    { name: 'فرقان',    code: '25',  count: 77  },
    { name: 'شعراء',    code: '26',  count: 227 },
    { name: 'نمل',      code: '27',  count: 93  },
    { name: 'قصص',      code: '28',  count: 88  },
    { name: 'عنکبوت',   code: '29',  count: 69  },
    { name: 'روم',      code: '30',  count: 60  },
    { name: 'لقمان',    code: '31',  count: 34  },
    { name: 'سجده',     code: '32',  count: 30  },
    { name: 'احزاب',    code: '33',  count: 73  },
    { name: 'سیاء',     code: '34',  count: 54  },
    { name: 'فاطر',     code: '35',  count: 45  },
    { name: 'یس',       code: '36',  count: 83  },
    { name: 'صافات',    code: '37',  count: 182 },
    { name: 'ص',        code: '38',  count: 88  },
    { name: 'زمر',      code: '39',  count: 75  },
    { name: 'غافر',     code: '40',  count: 85  },
    { name: 'فصلت',     code: '41',  count: 54  },
    { name: 'شوری',     code: '42',  count: 53  },
    { name: 'زخرف',     code: '43',  count: 89  },
    { name: 'دخان',     code: '44',  count: 59  },
    { name: 'جاثیه',    code: '45',  count: 37  },
    { name: 'احقاف',    code: '46',  count: 35  },
    { name: 'محمد',     code: '47',  count: 38  },
    { name: 'فتح',      code: '48',  count: 29  },
    { name: 'حجرات',    code: '49',  count: 18  },
    { name: 'ق',        code: '50',  count: 45  },
    { name: 'ذاریات',   code: '51',  count: 60  },
    { name: 'طور',      code: '52',  count: 49  },
    { name: 'نجم',      code: '53',  count: 62  },
    { name: 'قمر',      code: '54',  count: 55  },
    { name: 'رحمن',     code: '55',  count: 78  },
    { name: 'واقعه',    code: '56',  count: 96  },
    { name: 'حدید',     code: '57',  count: 29  },
    { name: 'مجادله',   code: '58',  count: 22  },
    { name: 'حشر',      code: '59',  count: 24  },
    { name: 'ممتحنه',   code: '60',  count: 13  },
    { name: 'صف',       code: '61',  count: 14  },
    { name: 'جمعه',     code: '62',  count: 11  },
    { name: 'منافقون',  code: '63',  count: 11  },
    { name: 'تغابن',    code: '64',  count: 18  },
    { name: 'طلاق',      code: '65',  count: 12  },
    { name: 'تحریم',    code: '66',  count: 12  },
    { name: 'ملک',      code: '67',  count: 30  },
    { name: 'قلم',      code: '68',  count: 52  },
    { name: 'حاقه',     code: '69',  count: 52  },
    { name: 'معارج',    code: '70',  count: 44  },
    { name: 'نوح',      code: '71',  count: 28  },
    { name: 'جن',       code: '72',  count: 28  },
    { name: 'مزمل',     code: '73',  count: 20  },
    { name: 'مدثر',     code: '74',  count: 56  },
    { name: 'قیامه',    code: '75',  count: 40  },
    { name: 'انسان',    code: '76',  count: 31  },
    { name: 'مرسلات',    code: '77',  count: 50  },
    { name: 'نبا',      code: '78',  count: 40  },
    { name: 'نازعات',   code: '79',  count: 46  },
    { name: 'عبس',      code: '80',  count: 42  },
    { name: 'تکویر',    code: '81',  count: 29  },
    { name: 'انفطار',   code: '82',  count: 19  },
    { name: 'مطفیفین',  code: '83',  count: 36  },
    { name: 'انشقاق',   code: '84',  count: 25  },
    { name: 'بروج',     code: '85',  count: 22  },
    { name: 'طارق',     code: '86',  count: 17  },
    { name: 'اعلی',     code: '87',  count: 19  },
    { name: 'غاشیه',    code: '88',  count: 26  },
    { name: 'فجر',      code: '89',  count: 30  },
    { name: 'بلد',      code: '90',  count: 20  },
    { name: 'شمس',      code: '91',  count: 15  },
    { name: 'لیل',      code: '92',  count: 21  },
    { name: 'ضحی',      code: '93',  count: 11  },
    { name: 'شرح',      code: '94',  count: 8   },
    { name: 'تین',      code: '95',  count: 8   },
    { name: 'علق',      code: '96',  count: 19  },
    { name: 'قدر',      code: '97',  count: 5   },
    { name: 'بینه',     code: '98',  count: 8   },
    { name: 'زلزله',    code: '99',  count: 8   },
    { name: 'عادیات',   code: '100', count: 11  },
    { name: 'قارعه',    code: '101', count: 11  },
    { name: 'تکاثر',    code: '102', count: 8   },
    { name: 'عصر',      code: '103', count: 3   },
    { name: 'همزه',     code: '104', count: 9   },
    { name: 'فیل',      code: '105', count: 5   },
    { name: 'قریش',     code: '106', count: 4   },
    { name: 'ماعون',    code: '107', count: 7   },
    { name: 'کوثر',     code: '108', count: 3   },
    { name: 'کافرون',   code: '109', count: 6   },
    { name: 'نصر',      code: '110', count: 3   },
    { name: 'مسد',      code: '111', count: 5   },
    { name: 'اخلاص',     code: '112', count: 4   },
    { name: 'فلق',      code: '113', count: 5   },
    { name: 'ناس',      code: '114', count: 6   },

]



export const fullSureh = () => {
    let newArray: Surah[] = [];
    asuar.map(surah => {
        newArray.push({...surah, fullName: `${surah.code} - ${surah.name}`})
    })    
    return newArray;
}